import { Fragment } from 'react';
import { Modal } from './ui/Modal';
import { Spinner } from './ui/Spinner';
import { Button } from './ui/Button';
import { Sparkles } from 'lucide-react';

interface AiReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: string | null;
  isLoading: boolean;
  error: string | null;
  onRetry: () => void;
}

function renderInline(text: string, keyPrefix: string) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  return parts.map((part, idx) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return (
        <strong key={`${keyPrefix}-${idx}`} className="font-semibold text-ink-900">
          {part.slice(2, -2)}
        </strong>
      );
    }
    return <Fragment key={`${keyPrefix}-${idx}`}>{part}</Fragment>;
  });
}


function renderReport(markdown: string) {
  const lines = markdown.split('\n');
  const elements: React.ReactNode[] = [];
  let listBuffer: string[] = [];

  const flushList = (key: string) => {
    if (listBuffer.length > 0) {
      elements.push(
        <ul key={key} className="list-disc pl-5 space-y-1 my-2">
          {listBuffer.map((item, idx) => (
            <li key={idx} className="text-sm text-ink-700 leading-relaxed">
              {renderInline(item, `li-${key}-${idx}`)}
            </li>
          ))}
        </ul>
      );
      listBuffer = [];
    }
  };

  lines.forEach((rawLine, idx) => {
    const line = rawLine.trim();

    if (!line) {
      flushList(`flush-${idx}`);
      return;
    }

    const bulletMatch = line.match(/^[-*]\s+(.*)/);
    if (bulletMatch) {
      listBuffer.push(bulletMatch[1]);
      return;
    }
    flushList(`flush-${idx}`);

    const h3Match = line.match(/^###\s+(.*)/);
    const h2Match = line.match(/^##\s+(.*)/);
    const h1Match = line.match(/^#\s+(.*)/);

    if (h3Match) {
      elements.push(
        <h3 key={idx} className="text-sm font-semibold text-ink-900 mt-4 mb-1">
          {renderInline(h3Match[1], `h3-${idx}`)}
        </h3>
      );
    } else if (h2Match) {
      elements.push(
        <h2 key={idx} className="text-base font-semibold text-ink-900 mt-4 mb-1">
          {renderInline(h2Match[1], `h2-${idx}`)}
        </h2>
      );
    } else if (h1Match) {
      elements.push(
        <h1 key={idx} className="text-lg font-semibold text-ink-900 mt-4 mb-1">
          {renderInline(h1Match[1], `h1-${idx}`)}
        </h1>
      );
    } else {
      elements.push(
        <p key={idx} className="text-sm text-ink-700 leading-relaxed mt-2">
          {renderInline(line, `p-${idx}`)}
        </p>
      );
    }
  });

  flushList('flush-end');
  return elements;
}

export function AiReportModal({ isOpen, onClose, report, isLoading, error, onRetry }: AiReportModalProps) {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="AI Financial Report" maxWidth="lg">
      {isLoading && (
        <div className="flex flex-col items-center justify-center py-10 gap-3">
          <Spinner size="lg" />
          <p className="text-sm text-ink-300">Analyzing your spending...</p>
        </div>
      )}

      {!isLoading && error && (
        <div className="flex flex-col items-center text-center py-8 gap-3">
          <p className="text-sm text-ink-700">{error}</p>
          <Button variant="secondary" onClick={onRetry}>Try again</Button>
        </div>
      )}

      {!isLoading && !error && report && (
        <div className="max-h-[60vh] overflow-y-auto pr-1">
          <div className="flex items-center gap-2 mb-3 text-brand-600">
            <Sparkles size={16} />
            <span className="text-xs font-medium uppercase tracking-wide">Generated by AI</span>
          </div>
          {renderReport(report)}
        </div>
      )}
    </Modal>
  );
}